project:
  type: website
  output-dir: docs

website:
  title: "Gab Chen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
          
      - text: Labs
        menu:
          - href: lab/lab0/lab0.qmd
            text: "Lab 0: Getting Started with dply"
          - href: lab/lab1/lab1.qmd
            text: "Lab 1: Census Data Exploration"
          - href: lab/lab2/lab2.qmd
            text: "Lab 2: Spatial Analysis and Visualization"


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
