project:
  type: website
  output-dir: docs

website:
  title: "Gab Chen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.html
            text: Week 1
          
      - text: Labs
        menu:
          - href: lab/lab0/lab0.qmd
            text: "Lab 0: Getting Started with dply"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
